In [1]:
#Dependencies
import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import time
# API Key
from config import apikey

In [2]:
#https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo
base_url = "https://www.alphavantage.co/query?"
params = {
    "function":"TIME_SERIES_WEEKLY",
    "symbol":"",   #REMOVE AFTER VERIFYING
    "apikey":apikey
}

# Read in the stock data set
#stock_data = pd.read_csv('Resources/Stocks.csv')
#stock_data.head()


#function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo

In [3]:
#Using this code after the csv was created
stock_data = pd.read_csv('500_stock_export.csv')
stock_data.head()

,Unnamed: 0,Symbol,Name,Sector,2019-10-04,2019-10-11,2019-10-18,2019-10-25,2019-11-01,2019-11-08,...,2020-01-17,2020-01-24,2020-01-31,2020-02-07,2020-02-14,2020-02-21,2020-02-28,2020-03-06,2020-03-13,2020-03-20
0,0,MMM,3M Company,Industrials,155.82,158.10,163.10,166.09,170.09,173.15,...,181.35,178.15,158.66,160.08,161.01,156.93,149.24,153.65,141.68,124.89
1,1,AOS,A.O. Smith Corp,Industrials,45.51,47.99,51.01,51.07,50.28,52.08,...,46.93,45.43,42.69,41.99,43.93,44.09,39.55,42.69,41.49,34.75
2,2,ABT,Abbott Laboratories,Health Care,81.99,79.63,82.79,81.65,82.66,83.74,...,89.00,90.40,87.14,87.87,89.66,87.45,77.03,81.74,81.65,68.00
3,3,ABBV,AbbVie Inc.,Health Care,74.66,73.63,76.46,76.53,81.75,85.21,...,88.00,83.54,81.02,92.29,94.05,94.96,85.71,88.82,85.37,68.82
4,4,ACN,Accenture plc,Information Technology,189.64,184.97,187.08,183.07,188.22,189.70,...,209.20,208.57,205.21,211.58,212.37,211.89,180.59,178.75,166.51,149.94

In [4]:
#Implement the weeks we will want to add to the columns

Start_Week = "2019-10-04"
End_Week = "2020-04-24"
x= Start_Week
weeks = []

In [5]:
hardcode_weeks = ["2019-10-04", "2019-10-11","2019-10-18", "2019-10-25", "2019-11-01", "2019-11-08",
                  "2019-11-15", "2019-11-22", "2019-11-29", "2019-12-06", "2019-12-13", "2019-12-20",
                  "2019-12-27", "2020-01-03", "2020-01-10", "2020-01-17", "2020-01-24", "2020-01-31",
                  "2020-02-07", "2020-02-14", "2020-02-21", "2020-02-28", "2020-03-06", "2020-03-13",
                  "2020-03-20", "2020-03-27", "2020-04-03", "2020-04-10", "2020-04-17", "2020-04-24"]

In [7]:
hardcode_weeks[-1]

'2020-04-24'

In [8]:
for item in hardcode_weeks:
    stock_data[item]=""

In [12]:
stock_data.to_csv("latest_stock_export.csv")

In [10]:
x = 0
for index, row in stock_data[0:].iterrows():
    x = x + 1
    params['symbol']=row["Symbol"]
    response = requests.get(base_url, params=params).json()
    
    for week in hardcode_weeks: 
        try:
            stock_data.loc[index,week]= response["Weekly Time Series"][week]["4. close"]
        except:
            pass
    if x == 5:
        x = 0
        time.sleep(61)
            
        
stock_data.to_csv("stock_export.csv",index=False)

PermissionError: [Errno 13] Permission denied: 'stock_export.csv'

In [ ]:
stock_data

In [24]:
edit_df = stock_data.copy()

In [25]:
edit_df.replace('', np.nan, inplace=True)

In [26]:
edit_df.dropna(how="any", inplace = True)

In [40]:
edit_df["Difference"] = edit_df[hardcode_weeks[0]]-edit_df[hardcode_weeks[-1]]

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [28]:
edit_df

,Unnamed: 0,Symbol,Name,Sector,2019-10-04,2019-10-11,2019-10-18,2019-10-25,2019-11-01,2019-11-08,...,2020-01-17,2020-01-24,2020-01-31,2020-02-07,2020-02-14,2020-02-21,2020-02-28,2020-03-06,2020-03-13,2020-03-20
0,0,MMM,3M Company,Industrials,155.8200,158.1000,163.1000,166.0900,170.0900,173.1500,...,181.3500,178.1500,158.6600,160.0800,161.0100,156.9300,149.2400,153.6500,141.6800,124.8900
1,1,AOS,A.O. Smith Corp,Industrials,45.5100,47.9900,51.0100,51.0700,50.2800,52.0800,...,46.9300,45.4300,42.6900,41.9900,43.9300,44.0900,39.5500,42.6900,41.4900,34.7500
2,2,ABT,Abbott Laboratories,Health Care,81.9900,79.6300,82.7900,81.6500,82.6600,83.7400,...,89.0000,90.4000,87.1400,87.8700,89.6600,87.4500,77.0300,81.7400,81.6500,68.0000
3,3,ABBV,AbbVie Inc.,Health Care,74.6600,73.6300,76.4600,76.5300,81.7500,85.2100,...,88.0000,83.5400,81.0200,92.2900,94.0500,94.9600,85.7100,88.8200,85.3700,68.8200
4,4,ACN,Accenture plc,Information Technology,189.6400,184.9700,187.0800,183.0700,188.2200,189.7000,...,209.2000,208.5700,205.2100,211.5800,212.3700,211.8900,180.5900,178.7500,166.5100,149.9400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,500,XYL,Xylem Inc.,Industrials,75.9700,77.6300,79.7800,83.3000,79.1200,77.3300,...,83.4600,81.4800,81.6600,84.2000,88.1400,88.5200,77.3400,81.2200,72.1200,59.8900
462,501,YUM,Yum! Brands Inc,Consumer Discretionary,114.6600,114.4500,112.3000,109.1000,99.6500,98.9000,...,105.4000,104.9800,105.7700,102.0400,105.2800,103.5100,89.2500,89.4000,78.4600,58.0800
463,502,ZBH,Zimmer Biomet Holdings,Health Care,134.4500,136.4400,137.6100,134.0700,138.2200,144.0000,...,149.3800,147.8000,147.9000,156.3900,160.4000,157.3900,136.1500,124.1000,97.8000,85.9800
464,503,ZION,Zions Bancorp,Financials,43.2000,44.0900,44.7200,47.9500,49.3450,51.0700,...,50.7400,46.6300,45.4900,46.2300,46.2600,45.4300,39.9500,35.2800,29.4200,25.5800
465,504,ZTS,Zoetis,Health Care,127.0500,128.4700,128.1200,124.3600,125.3400,117.8600,...,140.1600,136.3100,134.2100,138.9000,144.1700,142.2300,133.2300,137.0500,125.4800,100.9400

In [29]:
edit_df.to_csv("500_stock_export.csv",index=False)

In [30]:
sector_df = edit_df.copy()

In [31]:
sector_df = sector_df.drop(["Symbol","Name","Unnamed: 0"], axis=1)
sector_df = sector_df.set_index(["Sector"])
sector_df

,2019-10-04,2019-10-11,2019-10-18,2019-10-25,2019-11-01,2019-11-08,2019-11-15,2019-11-22,2019-11-29,2019-12-06,...,2020-01-17,2020-01-24,2020-01-31,2020-02-07,2020-02-14,2020-02-21,2020-02-28,2020-03-06,2020-03-13,2020-03-20
Sector,,,,,,,,,,,,,,,,,,,,,
Industrials,155.8200,158.1000,163.1000,166.0900,170.0900,173.1500,171.8800,167.6000,169.7700,171.4700,...,181.3500,178.1500,158.6600,160.0800,161.0100,156.9300,149.2400,153.6500,141.6800,124.8900
Industrials,45.5100,47.9900,51.0100,51.0700,50.2800,52.0800,50.7800,48.2000,48.4000,46.7900,...,46.9300,45.4300,42.6900,41.9900,43.9300,44.0900,39.5500,42.6900,41.4900,34.7500
Health Care,81.9900,79.6300,82.7900,81.6500,82.6600,83.7400,85.7100,83.7400,85.4500,85.4800,...,89.0000,90.4000,87.1400,87.8700,89.6600,87.4500,77.0300,81.7400,81.6500,68.0000
Health Care,74.6600,73.6300,76.4600,76.5300,81.7500,85.2100,88.6300,86.0500,87.7300,86.9800,...,88.0000,83.5400,81.0200,92.2900,94.0500,94.9600,85.7100,88.8200,85.3700,68.8200
Information Technology,189.6400,184.9700,187.0800,183.0700,188.2200,189.7000,196.8100,196.6600,201.1600,202.5500,...,209.2000,208.5700,205.2100,211.5800,212.3700,211.8900,180.5900,178.7500,166.5100,149.9400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Industrials,75.9700,77.6300,79.7800,83.3000,79.1200,77.3300,77.5500,76.8900,77.5100,75.3200,...,83.4600,81.4800,81.6600,84.2000,88.1400,88.5200,77.3400,81.2200,72.1200,59.8900
Consumer Discretionary,114.6600,114.4500,112.3000,109.1000,99.6500,98.9000,98.2800,97.6200,100.6700,98.7700,...,105.4000,104.9800,105.7700,102.0400,105.2800,103.5100,89.2500,89.4000,78.4600,58.0800
Health Care,134.4500,136.4400,137.6100,134.0700,138.2200,144.0000,146.7800,143.8200,145.2800,148.5300,...,149.3800,147.8000,147.9000,156.3900,160.4000,157.3900,136.1500,124.1000,97.8000,85.9800
Financials,43.2000,44.0900,44.7200,47.9500,49.3450,51.0700,49.5500,49.9600,49.7800,49.7100,...,50.7400,46.6300,45.4900,46.2300,46.2600,45.4300,39.9500,35.2800,29.4200,25.5800
Health Care,127.0500,128.4700,128.1200,124.3600,125.3400,117.8600,117.9200,119.8100,120.5200,121.7200,...,140.1600,136.3100,134.2100,138.9000,144.1700,142.2300,133.2300,137.0500,125.4800,100.9400

In [32]:
sector_df[hardcode_weeks]= sector_df[hardcode_weeks].apply(pd.to_numeric, errors = "coerce")

In [33]:
sector_df = sector_df.groupby(["Sector"]).mean()

In [34]:
sector_df

,2019-10-04,2019-10-11,2019-10-18,2019-10-25,2019-11-01,2019-11-08,2019-11-15,2019-11-22,2019-11-29,2019-12-06,...,2020-01-17,2020-01-24,2020-01-31,2020-02-07,2020-02-14,2020-02-21,2020-02-28,2020-03-06,2020-03-13,2020-03-20
Sector,,,,,,,,,,,,,,,,,,,,,
Consumer Discretionary,150.975779,152.346623,154.383571,155.682468,156.319610,154.446039,153.821948,153.502597,156.032727,156.328571,...,163.047078,159.644675,156.404481,159.324675,163.335455,161.617273,143.750649,140.200130,124.656039,104.178701
Consumer Staples,92.192167,91.533667,91.195833,90.782000,90.512667,90.793333,91.333333,91.538333,92.429333,93.057833,...,95.707667,95.204500,93.748000,95.787500,96.808333,96.178667,85.963000,91.549000,83.497333,77.262667
Energy,46.462593,47.197778,46.100741,48.623333,48.590000,49.938148,49.339259,48.618148,47.780741,48.567407,...,51.454074,48.728519,45.801852,46.324074,46.590000,46.731481,39.348519,35.187407,25.294074,20.560000
Financials,92.388333,92.811905,93.571905,94.597302,96.402143,98.492698,98.666349,98.798889,99.663651,100.096667,...,103.739683,102.195873,101.173016,104.230635,105.766667,104.361270,89.908095,87.252381,77.146984,63.810000
Health Care,155.743909,155.795818,159.419000,160.992273,165.174000,165.438364,169.808273,171.283818,173.360545,175.027636,...,184.018545,180.328545,172.708182,179.960182,183.956182,183.118909,164.644727,170.859636,156.790364,135.773818
Industrials,123.872109,125.941797,126.794375,129.086953,130.892656,132.775625,133.845000,133.004609,133.615938,132.783203,...,139.756094,138.620469,134.233750,137.693438,139.265312,137.736719,121.281250,119.519375,104.808281,85.316719
Information Technology,147.868881,149.027015,148.894179,151.500522,153.646119,156.361791,158.810746,156.718358,159.281045,159.450448,...,174.562687,174.548358,168.712836,174.194627,179.186567,175.416119,157.667910,155.551940,144.333955,123.820149
Materials,112.417273,114.131818,114.520000,116.207273,117.130455,118.960909,119.634545,117.525455,119.311364,119.506818,...,121.295455,119.685455,115.970455,120.777727,120.953182,119.479091,105.575909,108.830909,95.765909,81.130909
Real Estate,122.095312,121.188750,122.807813,121.790313,120.881562,116.390625,118.725000,117.303750,118.856250,118.557187,...,121.672812,122.815781,121.121875,123.436875,129.334688,129.368437,113.829688,119.804688,111.363750,85.029063
Telecommunication Services,36.316667,36.413333,37.320000,36.723333,37.546667,37.840000,37.993333,37.490000,37.370000,37.850000,...,37.523333,37.830000,36.906667,37.640000,36.886667,36.656667,33.816667,35.290000,32.920000,29.783333
Utilities,81.083846,79.808654,79.692885,79.938462,79.784615,76.430769,77.766538,77.886538,77.997692,78.197308,...,83.277692,85.280769,85.890769,85.496923,87.515000,87.189231,76.975769,83.161923,71.519231,58.891154

In [35]:
sector_df.to_csv("500_bysector_export.csv",index=False)

In [ ]:
#sector_df = sector_df.T

In [36]:
sector_df

,2019-10-04,2019-10-11,2019-10-18,2019-10-25,2019-11-01,2019-11-08,2019-11-15,2019-11-22,2019-11-29,2019-12-06,...,2020-01-17,2020-01-24,2020-01-31,2020-02-07,2020-02-14,2020-02-21,2020-02-28,2020-03-06,2020-03-13,2020-03-20
Sector,,,,,,,,,,,,,,,,,,,,,
Consumer Discretionary,150.975779,152.346623,154.383571,155.682468,156.319610,154.446039,153.821948,153.502597,156.032727,156.328571,...,163.047078,159.644675,156.404481,159.324675,163.335455,161.617273,143.750649,140.200130,124.656039,104.178701
Consumer Staples,92.192167,91.533667,91.195833,90.782000,90.512667,90.793333,91.333333,91.538333,92.429333,93.057833,...,95.707667,95.204500,93.748000,95.787500,96.808333,96.178667,85.963000,91.549000,83.497333,77.262667
Energy,46.462593,47.197778,46.100741,48.623333,48.590000,49.938148,49.339259,48.618148,47.780741,48.567407,...,51.454074,48.728519,45.801852,46.324074,46.590000,46.731481,39.348519,35.187407,25.294074,20.560000
Financials,92.388333,92.811905,93.571905,94.597302,96.402143,98.492698,98.666349,98.798889,99.663651,100.096667,...,103.739683,102.195873,101.173016,104.230635,105.766667,104.361270,89.908095,87.252381,77.146984,63.810000
Health Care,155.743909,155.795818,159.419000,160.992273,165.174000,165.438364,169.808273,171.283818,173.360545,175.027636,...,184.018545,180.328545,172.708182,179.960182,183.956182,183.118909,164.644727,170.859636,156.790364,135.773818
Industrials,123.872109,125.941797,126.794375,129.086953,130.892656,132.775625,133.845000,133.004609,133.615938,132.783203,...,139.756094,138.620469,134.233750,137.693438,139.265312,137.736719,121.281250,119.519375,104.808281,85.316719
Information Technology,147.868881,149.027015,148.894179,151.500522,153.646119,156.361791,158.810746,156.718358,159.281045,159.450448,...,174.562687,174.548358,168.712836,174.194627,179.186567,175.416119,157.667910,155.551940,144.333955,123.820149
Materials,112.417273,114.131818,114.520000,116.207273,117.130455,118.960909,119.634545,117.525455,119.311364,119.506818,...,121.295455,119.685455,115.970455,120.777727,120.953182,119.479091,105.575909,108.830909,95.765909,81.130909
Real Estate,122.095312,121.188750,122.807813,121.790313,120.881562,116.390625,118.725000,117.303750,118.856250,118.557187,...,121.672812,122.815781,121.121875,123.436875,129.334688,129.368437,113.829688,119.804688,111.363750,85.029063
Telecommunication Services,36.316667,36.413333,37.320000,36.723333,37.546667,37.840000,37.993333,37.490000,37.370000,37.850000,...,37.523333,37.830000,36.906667,37.640000,36.886667,36.656667,33.816667,35.290000,32.920000,29.783333
Utilities,81.083846,79.808654,79.692885,79.938462,79.784615,76.430769,77.766538,77.886538,77.997692,78.197308,...,83.277692,85.280769,85.890769,85.496923,87.515000,87.189231,76.975769,83.161923,71.519231,58.891154

In [37]:
x=sector_df.index
y=sector_df["Difference"]

plt.bar(x, y, align='center', alpha=0.5)
plt.title("Sector Differences per Sector")
plt.xlabel("Sectors")
plt.ylabel("Stock Price Difference ($)")
plt.xticks(rotation=90)

plt.show()

KeyError: 'Difference'